library(scales)

rm(list=ls())

wd <- "/users/andrew leader/Documents/GitHub/Leader_et_al/"
setwd(wd)

plot_dir <- "output/figures"

#Load results of TCGA LCAM scoring analysis - generated by the other figure_6 script
load("output/statistics/TCGA_LCAM_scores.rd")


gene_lists <- read.csv("input_tables/table_s5_signature_scores.csv",h=1,stringsAsFactors = F)
gene_list <- list()
gene_list$fibroblast_tumor <- gene_lists[,"Figure.S6...CAF"]
gene_list$lymphatic <- gene_lists[,"Figure.S6...Lymphatics"]
gene_list$blood_endo_normal <- gene_lists[,"Figure.S6...Normal.BEC"]
gene_list$blood_endo_tumor <- gene_lists[,"Figure.S6...Tumor.BEC"]
gene_list$fibroblast_normal <- gene_lists[,"Figure.S6...Normal.fibroblast"]
rm(gene_lists)

gene_list <- lapply(gene_list,function(x){x <- x[!x==""]})

#load("/users/andrew leader/google drive/merad/Leader_et_al_figure_scripts/Lambrechts_stromal/stromal_gene_lists.rd")

open_plot <- function(fn){
png(fn,height=4,width=4,units="in",res=300,bg="transparent")
  par(mgp=c(2,1,0))
}

stromal_scores <- lapply(gene_list,function(x){colMeans(z_mat[x,])})

stromal_scores <- do.call(cbind,stromal_scores)

cor(stromal_scores[names(score1),],score1-score2)


open_plot(file.path(plot_dir,"figure_s6g.png"))
plot(stromal_scores[names(score1),"fibroblast_tumor"],score1-score2,
     ylab="LCAM score",xlab="CAF score",pch=16,col=alpha(1,0.4))
mtext("CAF",cex=1.5)
res <- cor.test(stromal_scores[names(score1),"fibroblast_tumor"],score1-score2)
legend("bottomright",c(paste("r=",signif(res$estimate,2),sep=""),paste("p=",signif(res$p.value,2),sep="")),bg="white")
dev.off()

open_plot(file.path(plot_dir,"figure_s6i_right.png"))
plot(stromal_scores[names(score1),"lymphatic"],score1-score2,
     ylab="LCAM score",xlab="Lymphatics score",pch=16,col=alpha(1,0.4))
mtext("Lymphatics",cex=1.5)
res <- cor.test(stromal_scores[names(score1),"lymphatic"],score1-score2)
legend("bottomright",c(paste("r=",signif(res$estimate,2),sep=""),paste("p=",signif(res$p.value,2),sep="")),bg="white")
dev.off()

open_plot(file.path(plot_dir,"figure_s6i_center.png"))
plot(stromal_scores[names(score1),"blood_endo_normal"],score1-score2,
     ylab="LCAM score",xlab="Normal BEC score",pch=16,col=alpha(1,0.4))
mtext("Normal BEC",cex=1.5)
res <- cor.test(stromal_scores[names(score1),"blood_endo_normal"],score1-score2)
legend("bottomleft",c(paste("r=",signif(res$estimate,2),sep=""),paste("p=",signif(res$p.value,2),sep="")),bg="white")
dev.off()

open_plot(file.path(plot_dir,"figure_s6i_left.png"))
plot(stromal_scores[names(score1),"blood_endo_tumor"],score1-score2,
     ylab="LCAM score",xlab="Tumor BEC score",pch=16,col=alpha(1,0.4))
mtext("Tumor BEC",cex=1.5)
res <- cor.test(stromal_scores[names(score1),"blood_endo_tumor"],score1-score2)
legend("bottomleft",c(paste("r=",signif(res$estimate,2),sep=""),paste("p=",signif(res$p.value,2),sep="")),bg="white")
dev.off()

open_plot(file.path(plot_dir,"figure_s6h.png"))
plot(stromal_scores[names(score1),"fibroblast_normal"],score1-score2,
     ylab="LCAM score",xlab="Normal Fibroblast score",pch=16,col=alpha(1,0.4))
mtext("Normal Fibroblast",cex=1.5)
res <- cor.test(stromal_scores[names(score1),"fibroblast_normal"],score1-score2)
legend("bottomleft",c(paste("r=",signif(res$estimate,2),sep=""),paste("p=",signif(res$p.value,2),sep="")),bg="white")
dev.off()

open_plot(file.path(plot_dir,"figure_s6g.png"))
plot(stromal_scores[names(score1),"fibroblast_tumor"],score1-score2,
     ylab="LCAM score",xlab="CAF score",pch=16,col=alpha(1,0.4))
mtext("CAF",cex=1.5)
res <- cor.test(stromal_scores[names(score1),"fibroblast_tumor"],score1-score2)
legend("bottomright",c(paste("r=",signif(res$estimate,2),sep=""),paste("p=",signif(res$p.value,2),sep="")),bg="white")
dev.off()


open_plot(file.path(plot_dir,"figure_6b.png"))
plot(stromal_scores[names(score1),"fibroblast_tumor"]-stromal_scores[names(score1),"fibroblast_normal"],score1-score2,
     ylab="LCAM score",xlab="CAF - Normal Fibroblast score",pch=16,col=alpha(1,0.4))
mtext("CAF-Normal Fibroblast",cex=1.5)
res <- cor.test(stromal_scores[names(score1),"fibroblast_tumor"]-stromal_scores[names(score1),"fibroblast_normal"],score1-score2)
legend("bottomright",c(paste("r=",signif(res$estimate,2),sep=""),paste("p=",signif(res$p.value,2),sep="")),bg="white")
dev.off()
